### ISSUE TITLE
Project is missing a license

### ISSUE THREAD

**Issue by erikns** [erikns/webpoll#2]
The project should decide on a license.

**Comment by erikns** [comment]
My suggestion is the GPL v3 👍

**Comment by magnusdk** [comment]
I'm with you on that 
![image](https://cloud.githubusercontent.com/assets/15210698/26286361/01f2ddf2-3e64-11e7-8cd7-74486526ad57.png)

**Comment by Thomashrb** [comment]
Added GPL v3, closing issue
